version: "3"
networks:
    webnet:
services:
    nginx:
        image: nginx:1.10.1-alpine
        ports:
            - "80:80"
        networks:
            - webnet
        volumes:
            #- ".:/var/www/html"
            - "./nginx/log:/var/log/nginx"
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
            - "./webroot:/webroot"
    phpfpm:
        image: php:7.1.9-fpm-alpine
        ports:
            - "9000:9000"
        networks:
            - webnet
        volumes:
            - "./phpfpm/log:/usr/local/var/log"
            - "./webroot:/webroot"
            - "./phpfpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
